const Data={
    "edges_list": [
      {
        "device_b_ip": "10.5.0.3", 
        "in_between": "router-interface",
        "download": 178.43, 
        "download_utilization": 1.784, 
        "errors": "in-0, out-0", 
        "high_speed": 10000.0, 
        "id": "edge-1", 
        "interface_a": "TenGigE0/0/0/12.922", 
        "interface_b": "be10.922", 
        "label": "40 GB", 
        "packet_drops": "in-3201, out-0", 
        "source": "r1", 
        "source_type": "router",
        "source_ip": "10.64.0.3", 
        "status": "Up", 
        "target": "i1", 
        "target_type": "interface",
        "target_ip": "10.5.0.3", 
        "upload": 809.96, 
        "upload_utilization": 8.1
      }, 
      {
        "device_b_ip": "10.70.0.3", 
        "in_between": "router-interface",
        "download": 0.03, 
        "download_utilization": 0.003, 
        "errors": "in-0, out-0", 
        "high_speed": 1000, 
        "id": "edge-2", 
        "interface_a": "TenGigE0/0/0/12.916", 
        "interface_b": "Gi0/0/3.916", 
        "label": "40 GB", 
        "packet_drops": "in-281, out-0", 
        "source": "r2", 
        "source_type":"router",
        "source_ip": "10.64.0.3", 
        "status": "Up", 
        "target": "i2", 
        "target_type": "interface",
        "target_ip": "10.70.0.3", 
        "upload": 0.02, 
        "upload_utilization": 0.002
      }, 
      {
        "device_b_ip": "10.14.106.151", 
        "in_between": "router-interface",
        "download": 5164.07, 
        "download_utilization": 25.82, 
        "errors": "in-0, out-0", 
        "high_speed": 20000.0, 
        "id": "edge-3", 
        "interface_a": "Bundle-Ether22.900", 
        "interface_b": "Bundle-Ether22.900", 
        "label": "40 GB", 
        "packet_drops": "in-0, out-0", 
        "source": "r3", 
        "source_type":"router",
        "source_ip": "10.64.0.3", 
        "status": "Up", 
        "target": "i3", 
        "target_type": "interface",
        "target_ip": "10.14.106.151", 
        "upload": 4825.7, 
        "upload_utilization": 24.129
      }, 
      {
        "device_b_ip": "10.67.0.5", 
        "in_between": "router-interface",
        "download": 2106.96, 
        "download_utilization": 21.07, 
        "errors": "in-0, out-0", 
        "high_speed": 10000.0, 
        "id": "edge-4", 
        "interface_a": "TenGigE0/0/0/31.930", 
        "interface_b": "Te0/0/0/23.930", 
        "label": "40 GB", 
        "packet_drops": "in-0, out-0", 
        "source": "r4", 
        "source_type":"router",
        "source_ip": "10.64.0.3", 
        "status": "Up", 
        "target": "i4", 
        "target_type": "interface",
        "target_ip": "10.67.0.5", 
        "upload": 6415.24, 
        "upload_utilization": 64.152
      }, 
      {
        "device_b_ip": "10.73.0.3", 
        "in_between": "router-interface",
        "download": 0.02, 
        "download_utilization": 0.0, 
        "errors": "in-0, out-0", 
        "high_speed": 10000.0, 
        "id": "edge-5", 
        "interface_a": "TenGigE0/0/0/12.920", 
        "interface_b": "Te1/1/0.920", 
        "label": "40 GB", 
        "packet_drops": "in-13, out-0", 
        "source": "r5", 
        "source_type":"router",
        "source_ip": "10.64.0.3", 
        "status": "Up", 
        "target": "i5", 
        "target_type": "interface",
        "target_ip": "10.73.0.3", 
        "upload": 0.02, 
        "upload_utilization": 0.0
      }, 
      {
        "device_b_ip": "10.8.160.3", 
        "in_between": "router-interface",
        "download": 0.14, 
        "download_utilization": 0.014, 
        "errors": "in-0, out-0", 
        "high_speed": 1000, 
        "id": "edge-6", 
        "interface_a": "TenGigE0/0/0/12.914", 
        "interface_b": "Gi0/3/1.914", 
        "label": "40 GB", 
        "packet_drops": "in-694, out-0", 
        "source": "r6", 
        "source_type":"router",
        "source_ip": "10.64.0.3", 
        "status": "Up", 
        "target": "i6", 
        "target_type": "interface",
        "target_ip": "10.8.160.3", 
        "upload": 0.04, 
        "upload_utilization": 0.004
      }, 
      {
        "device_b_ip": "10.6.0.134", 
        "in_between": "router-interface",
        "download": 88.39, 
        "download_utilization": 8.839, 
        "errors": "in-0, out-0", 
        "high_speed": 1000, 
        "id": "edge-7", 
        "interface_a": "TenGigE0/0/0/12.908", 
        "interface_b": "Gi4/11.908", 
        "label": "40 GB", 
        "packet_drops": "in-7697, out-0", 
        "source": "r7", 
        "source_type":"router",
        "source_ip": "10.64.0.3", 
        "status": "Up", 
        "target": "i7", 
        "target_type": "interface",
        "target_ip": "10.6.0.134", 
        "upload": 31.66, 
        "upload_utilization": 3.166
      }, 
      {
        "device_b_ip": "10.68.0.3", 
        "in_between": "router-interface",
        "download": 17.06, 
        "download_utilization": 1.706, 
        "errors": "in-0, out-0", 
        "high_speed": 1000, 
        "id": "edge-8", 
        "interface_a": "TenGigE0/0/0/12.910", 
        "interface_b": "Gi1/4.910", 
        "label": "40 GB", 
        "packet_drops": "in-1962, out-0", 
        "source": "r8", 
        "source_type":"router",
        "source_ip": "10.64.0.3", 
        "status": "Up", 
        "target": "i8", 
        "target_type": "interface",
        "target_ip": "10.68.0.3", 
        "upload": 0.41, 
        "upload_utilization": 0.041
      }, 
      {
        "device_b_ip": "10.14.106.151", 
        "in_between": "router-interface",
        "download": 24.05, 
        "download_utilization": 0.12, 
        "errors": "in-0, out-0", 
        "high_speed": 20000.0, 
        "id": "edge-9", 
        "interface_a": " Bundle-Ether1000", 
        "interface_b": " Bundle-Ether1000", 
        "label": "40 GB", 
        "packet_drops": "in-1654, out-0", 
        "source": "r9", 
        "source_type":"router",
        "source_ip": "10.64.0.3", 
        "status": "Up", 
        "target": "i9", 
        "target_type": "interface",
        "target_ip": "10.14.106.151", 
        "type": "straight", 
        "upload": 67.39, 
        "upload_utilization": 0.337
      }, 
      {
        "device_b_ip": "10.5.0.4", 
        "in_between": "router-interface",
        "download": 0.01, 
        "download_utilization": 0.0, 
        "errors": "in-0, out-0", 
        "high_speed": 10000.0, 
        "id": "edge-10", 
        "interface_a": "Te0/0/0/22.923", 
        "interface_b": "BE10.923", 
        "label": "40 GB", 
        "packet_drops": "in-0, out-0", 
        "source": "r10",
        "source_type":"router", 
        "source_ip": "10.66.0.3", 
        "status": "Up", 
        "target": "i10", 
        "target_type": "interface",
        "target_ip": "10.5.0.4", 
        "upload": 0.01, 
        "upload_utilization": 0.0
      }, 
      {
        "device_b_ip": "10.70.0.4", 
        "in_between": "router-interface",
        "download": 0.01, 
        "download_utilization": 0.001, 
        "errors": "in-0, out-0", 
        "high_speed": 1000, 
        "id": "edge-11", 
        "interface_a": "Te0/0/0/22.917", 
        "interface_b": "Gi0/0/3.917 ", 
        "label": "40 GB", 
        "packet_drops": "in-1, out-0", 
        "source": "r11",
        "source_type":"router", 
        "source_ip": "10.66.0.3", 
        "status": "Up", 
        "target": "i11", 
        "target_type": "interface",
        "target_ip": "10.70.0.4", 
        "upload": 0.01, 
        "upload_utilization": 0.001
      }, 
      {
        "device_b_ip": "10.14.106.152", 
        "in_between": "router-interface",
        "download": 3074.74, 
        "download_utilization": 15.374, 
        "errors": "in-0, out-0", 
        "high_speed": 20000.0, 
        "id": "edge-12", 
        "interface_a": "BE22.900", 
        "interface_b": "BE22.900", 
        "label": "40 GB", 
        "packet_drops": "in-0, out-0", 
        "source": "r12",
        "source_type":"router", 
        "source_ip": "10.66.0.3", 
        "status": "Up", 
        "target": "i12", 
        "target_type": "interface",
        "target_ip": "10.14.106.152", 
        "upload": 2303.96, 
        "upload_utilization": 11.52
      }, 
      {
        "device_b_ip": "10.67.0.6", 
        "in_between": "router-interface",
        "download": 0.01, 
        "download_utilization": 0.0, 
        "errors": "in-0, out-0", 
        "high_speed": 10000.0, 
        "id": "edge-13", 
        "interface_a": "Te0/0/0/31.931", 
        "interface_b": "Te0/0/0/23.931", 
        "label": "40 GB", 
        "packet_drops": "in-0, out-0", 
        "source": "r13",
        "source_type":"router", 
        "source_ip": "10.66.0.3", 
        "status": "Up", 
        "target": "i13", 
        "target_type": "interface",
        "target_ip": "10.67.0.6", 
        "upload": 0.01, 
        "upload_utilization": 0.0
      }, 
      {
        "device_b_ip": "10.73.0.4", 
        "download": 0.02, 
        "in_between": "interface-community",
        "download_utilization": 0.0, 
        "errors": "in-0, out-0", 
        "high_speed": 10000.0, 
        "id": "edge-14", 
        "interface_a": "Te0/0/0/22.921", 
        "interface_b": "Te1/1/0.921", 
        "label": "40 GB", 
        "packet_drops": "in-2, out-0", 
        "source": "c1", 
        "source_type":"community",
        "source_ip": "10.66.0.3", 
        "status": "Up", 
        "target": "i1", 
        "target_type":"interface",
        "target_ip": "10.73.0.4", 
        "upload": 0.02, 
        "upload_utilization": 0.0
      }, 
      {
        "device_b_ip": "10.8.160.4", 
        "download": 0.01, 
        "in_between": "interface-community",
        "download_utilization": 0.001, 
        "errors": "in-0, out-0", 
        "high_speed": 1000, 
        "id": "edge-15", 
        "interface_a": "Te0/0/0/22.915", 
        "interface_b": "Gi0/3/1.915", 
        "label": "40 GB", 
        "packet_drops": "in-1, out-0", 
        "source": "c2", 
        "source_type":"community",
        "source_ip": "10.66.0.3", 
        "status": "Up", 
        "target": "i2", 
        "target_type":"interface",
        "target_ip": "10.8.160.4", 
        "upload": 0.01, 
        "upload_utilization": 0.001
      }, 
      {
        "device_b_ip": "10.6.0.135", 
        "download": 0.01, 
        "in_between": "interface-community",
        "download_utilization": 0.001, 
        "errors": "in-0, out-0", 
        "high_speed": 1000, 
        "id": "edge-16", 
        "interface_a": "Te0/0/0/22.909", 
        "interface_b": "Gi4/11.909", 
        "label": "40 GB", 
        "packet_drops": "in-2, out-0", 
        "source": "c3", 
        "source_type":"community",
        "source_ip": "10.66.0.3", 
        "status": "Up", 
        "target": "i3", 
        "target_type":"interface",
        "target_ip": "10.6.0.135", 
        "upload": 0.01, 
        "upload_utilization": 0.001
      }, 
      {
        "device_b_ip": "10.68.0.4", 
        "download": 0.01, 
        "in_between": "interface-community",
        "download_utilization": 0.001, 
        "errors": "in-0, out-0", 
        "high_speed": 1000, 
        "id": "edge-17", 
        "interface_a": "Te0/0/0/22.911", 
        "interface_b": "Gi1/4.911", 
        "label": "40 GB", 
        "packet_drops": "in-2, out-0", 
        "source": "c4", 
        "source_type":"community",
        "source_ip": "10.66.0.3", 
        "status": "Up", 
        "target": "i4", 
        "target_type":"interface",
        "target_ip": "10.68.0.4", 
        "upload": 0.01, 
        "upload_utilization": 0.001
      }, 
      {
        "device_b_ip": "10.84.0.3", 
        "download": 0.79, 
        "in_between": "interface-community",
        "download_utilization": 0.079, 
        "errors": "in-0, out-0", 
        "high_speed": 1000, 
        "id": "edge-18", 
        "interface_a": "TenGigabitEthernet1/1/0.710", 
        "interface_b": "Gi3/1.710", 
        "label": "40 GB", 
        "packet_drops": "in-0, out-0", 
        "source": "c5", 
        "source_type":"community",
        "source_ip": "10.83.0.3", 
        "status": "Up", 
        "target": "i5", 
        "target_type":"interface",
        "target_ip": "10.84.0.3", 
        "upload": 0.19, 
        "upload_utilization": 0.019
      }, 
      {
        "device_b_ip": "10.81.0.3", 
        "download": 92.52, 
        "in_between": "interface-community",
        "download_utilization": 9.252, 
        "errors": "in-0, out-0", 
        "high_speed": 1000, 
        "id": "edge-19", 
        "interface_a": "TenGigabitEthernet1/1/0.706", 
        "interface_b": "Gi0/2/0.706", 
        "label": "40 GB", 
        "packet_drops": "in-0, out-0", 
        "source": "c6", 
        "source_type":"community",
        "source_ip": "10.83.0.3", 
        "status": "Up", 
        "target": "i6", 
        "target_type":"interface",
        "target_ip": "10.81.0.3", 
        "upload": 148.68, 
        "upload_utilization": 14.868
      }, 
      {
        "device_b_ip": "10.85.0.3", 
        "download": 15.29, 
        "in_between": "interface-community",
        "download_utilization": 1.529, 
        "errors": "in-0, out-0", 
        "high_speed": 1000, 
        "id": "edge-20", 
        "interface_a": "TenGigabitEthernet1/1/0.704", 
        "interface_b": "Gi0/0/2.704", 
        "label": "40 GB", 
        "packet_drops": "in-0, out-0", 
        "source": "c7", 
        "source_type":"community",
        "source_ip": "10.83.0.3", 
        "status": "Up", 
        "target": "i7", 
        "target_type":"interface",
        "target_ip": "10.85.0.3", 
        "upload": 0.35, 
        "upload_utilization": 0.035
      }, 
      {
        "device_b_ip": "10.87.0.3", 
        "download": 3.83, 
        "in_between": "interface-community",
        "download_utilization": 0.383, 
        "errors": "in-0, out-0", 
        "high_speed": 1000, 
        "id": "edge-21", 
        "interface_a": "TenGigabitEthernet1/1/0.702", 
        "interface_b": "Gi0/0/2.702", 
        "label": "40 GB", 
        "packet_drops": "in-0, out-0", 
        "source": "c8", 
        "source_type":"community",
        "source_ip": "10.83.0.3", 
        "status": "Up", 
        "target": "i8", 
        "target_type":"interface",
        "target_ip": "10.87.0.3", 
        "upload": 0.26, 
        "upload_utilization": 0.026
      }, 
      {
        "device_b_ip": "10.82.0.3", 
        "download": 6.71, 
        "in_between": "interface-community",
        "download_utilization": 0.671, 
        "errors": "in-0, out-0", 
        "high_speed": 1000, 
        "id": "edge-22", 
        "interface_a": "TenGigabitEthernet1/1/0.918", 
        "interface_b": "Gi0/1/0.918", 
        "label": "40 GB", 
        "packet_drops": "in-0, out-0", 
        "source": "c9", 
        "source_type":"community",
        "source_ip": "10.83.0.3", 
        "status": "Up", 
        "target": "i9", 
        "target_type":"interface",
        "target_ip": "10.82.0.3", 
        "upload": 0.44, 
        "upload_utilization": 0.044
      }, 
      {
        "device_b_ip": "10.22.0.153", 
        "download": 25.81, 
        "in_between": "interface-community",
        "download_utilization": 2.581, 
        "errors": "in-0, out-0", 
        "high_speed": 1000, 
        "id": "edge-23", 
        "interface_a": "TenGigabitEthernet1/1/0.700", 
        "interface_b": "Gi0/2/0.700 ", 
        "label": "40 GB", 
        "packet_drops": "in-0, out-0", 
        "source": "c10",
        "source_type":"community", 
        "source_ip": "10.83.0.3", 
        "status": "Up", 
        "target": "i10", 
        "target_type":"interface",
        "target_ip": "10.22.0.153", 
        "upload": 0.74, 
        "upload_utilization": 0.074
      }, 
      {
        "device_b_ip": "10.20.0.3", 
        "download": 0.19, 
        "in_between": "interface-community",
        "download_utilization": 0.019, 
        "errors": "in-0, out-0", 
        "high_speed": 1000.0, 
        "id": "edge-24", 
        "interface_a": "GigabitEthernet0/1/3", 
        "interface_b": "GigabitEthernet0/1/3", 
        "label": "40 GB", 
        "packet_drops": "in-0, out-0", 
        "source": "c11",
        "source_type":"community", 
        "source_ip": "10.83.0.3", 
        "status": "Up", 
        "target": "i11", 
        "target_type":"interface",
        "target_ip": "10.20.0.3", 
        "upload": 0.11, 
        "upload_utilization": 0.011
      }, 
      {
        "device_b_ip": "10.20.0.4", 
        "download": 0.01, 
        "in_between": "interface-community",
        "download_utilization": 0.001, 
        "errors": "in-0, out-0", 
        "high_speed": 1000.0, 
        "id": "edge-25", 
        "interface_a": "GigabitEthernet0/0/0/1", 
        "interface_b": " Gig0/1/0", 
        "label": "40 GB", 
        "packet_drops": "in-95, out-0", 
        "source": "c12",
        "source_type":"community", 
        "source_ip": "10.78.0.3", 
        "status": "Up", 
        "target": "i12", 
        "target_type":"interface",
        "target_ip": "10.20.0.4", 
        "upload": 0.01, 
        "upload_utilization": 0.001
      }, 
      {
        "device_b_ip": "10.22.0.149", 
        "download": 0.01, 
        "in_between": "interface-community",
        "download_utilization": 0.001, 
        "errors": "in-0, out-0", 
        "high_speed": 1000, 
        "id": "edge-26", 
        "interface_a": "TenGigE0/0/0/22.714", 
        "interface_b": "Gi0/2/0.714", 
        "label": "40 GB", 
        "packet_drops": "in-4, out-0", 
        "source": "c13",
        "source_type":"community", 
        "source_ip": "10.78.0.3", 
        "status": "Up", 
        "target": "i13", 
        "target_type":"interface",
        "target_ip": "10.22.0.149", 
        "upload": 0.01, 
        "upload_utilization": 0.001
      }, 
      {
        "in_between": "router-interface",
        "device_b_ip": "10.87.0.4", 
        "download": 0.01, 
        "download_utilization": 0.001, 
        "errors": "in-0, out-0", 
        "high_speed": 1000, 
        "id": "edge-27", 
        "interface_a": "TenGigE0/0/0/22.715", 
        "interface_b": "Gi0/0/2.715", 
        "label": "40 GB", 
        "packet_drops": "in-4, out-0", 
        "source": "r1", 
        "source_type":"router",
        "source_ip": "10.78.0.3", 
        "status": "Up", 
        "target": "i2", 
        "target_type":"interface",
        "target_ip": "10.87.0.4", 
        "upload": 0.01, 
        "upload_utilization": 0.001
      }, 
      {
        "in_between": "interface-community",
        "device_b_ip": "10.85.0.4", 
        "download": 0.01, 
        "download_utilization": 0.001, 
        "errors": "in-0, out-0", 
        "high_speed": 1000, 
        "id": "edge-28", 
        "interface_a": "TenGigE0/0/0/22.716", 
        "interface_b": "Gi0/0/2.716", 
        "label": "40 GB", 
        "packet_drops": "in-4, out-1", 
        "source": "c2",
        "source_type":"community", 
        "source_ip": "10.78.0.3", 
        "status": "Up", 
        "target": "i1",
        "target_type":"interface", 
        "target_ip": "10.85.0.4", 
        "upload": 0.01, 
        "upload_utilization": 0.001
      }, 
      {
        "in_between": "interface-community",
        "device_b_ip": "10.81.0.4", 
        "download": 0.01, 
        "download_utilization": 0.001, 
        "errors": "in-0, out-0", 
        "high_speed": 1000, 
        "id": "edge-29", 
        "interface_a": "TenGigE0/0/0/22.717", 
        "interface_b": "Gi0/2/0.717", 
        "label": "40 GB", 
        "packet_drops": "in-4, out-0", 
        "source": "c3", 
        "source_type":"community",
        "source_ip": "10.78.0.3", 
        "status": "Up", 
        "target": "i1",
        "target_type":"interface", 
        "target_ip": "10.81.0.4", 
        "upload": 0.01, 
        "upload_utilization": 0.001
      }, 
      {
        "in_between": "interface-community",
        "device_b_ip": "10.84.0.4", 
        "download": 0.01, 
        "download_utilization": 0.001, 
        "errors": "in-0, out-0", 
        "high_speed": 1000, 
        "id": "edge-30", 
        "interface_a": "TenGigE0/0/0/22.719", 
        "interface_b": "Gi3/1.719", 
        "label": "40 GB", 
        "packet_drops": "in-4, out-0", 
        "source": "c14", 
        "source_type":"community",
        "source_ip": "10.78.0.3", 
        "status": "Up", 
        "target": "i13", 
        "target_type":"interface",
        "target_ip": "10.84.0.4", 
        "upload": 0.01, 
        "upload_utilization": 0.001
      }, 
      {
        "in_between": "interface-community",
        "device_b_ip": "10.82.0.4", 
        "download": 0.01, 
        "download_utilization": 0.001, 
        "errors": "in-0, out-0", 
        "high_speed": 1000, 
        "id": "edge-31", 
        "interface_a": "TenGigE0/0/0/22.721", 
        "interface_b": "Gi0/1/0.721", 
        "label": "40 GB", 
        "packet_drops": "in-4, out-0", 
        "source": "c15", 
        "source_type":"community",
        "source_ip": "10.78.0.3", 
        "status": "Up", 
        "target": "i10",
        "target_type":"interface",
        "target_ip": "10.82.0.4", 
        "upload": 0.01, 
        "upload_utilization": 0.001
      }, 
      {
        "in_between": "interface-community",
        "device_b_ip": "10.32.0.3", 
        "download": 65.49, 
        "download_utilization": 0.655, 
        "errors": "in-0, out-0", 
        "high_speed": 10000.0, 
        "id": "edge-32", 
        "interface_a": "Te0/0/0/22.800", 
        "interface_b": "Te4/2.800", 
        "label": "40 GB", 
        "packet_drops": "in-2474, out-0", 
        "source": "c16",
        "source_type":"community",
        "source_ip": "10.42.0.3", 
        "status": "Up", 
        "target": "i9",
        "target_type":"interface",
        "target_ip": "10.32.0.3", 
        "upload": 14.1, 
        "upload_utilization": 0.141
      }, 
      {
        "in_between": "interface-community",
        "device_b_ip": "10.76.0.3", 
        "download": 87.21, 
        "download_utilization": 8.721, 
        "errors": "in-0, out-0", 
        "high_speed": 1000, 
        "id": "edge-33", 
        "interface_a": "Te0/0/0/22.810", 
        "interface_b": "Gi1/3/7.810", 
        "label": "40 GB", 
        "packet_drops": "in-24303, out-0", 
        "source": "c17",
        "source_type":"community",
        "source_ip": "10.42.0.3", 
        "status": "Up", 
        "target": "i11",
        "target_type":"interface",
        "target_ip": "10.76.0.3", 
        "upload": 12.95, 
        "upload_utilization": 1.295
      }, 
      // {
      //   "device_b_ip": "10.35.0.3", 
      //   "download": 0.01, 
      //   "download_utilization": 0.001, 
      //   "errors": "in-0, out-0", 
      //   "high_speed": 1000, 
      //   "id": "edge-34", 
      //   "interface_a": "Te0/0/0/22.808", 
      //   "interface_b": "Gi0/0/3.808", 
      //   "label": "40 GB", 
      //   "packet_drops": "in-698, out-0", 
      //   "source": "ADAM-ECOR-CI-COM-001", 
      //   "source_ip": "10.42.0.3", 
      //   "status": "Up", 
      //   "target": "", 
      //   "target_ip": "10.35.0.3", 
      //   "upload": 0.01, 
      //   "upload_utilization": 0.001
      // }, 
      // {
      //   "device_b_ip": "10.32.0.4", 
      //   "download": 0.01, 
      //   "download_utilization": 0.0, 
      //   "errors": "in-0, out-0", 
      //   "high_speed": 10000.0, 
      //   "id": "edge-35", 
      //   "interface_a": "Te0/0/0/22.801", 
      //   "interface_b": "Te4/2.801", 
      //   "label": "40 GB", 
      //   "packet_drops": "in-2, out-0", 
      //   "source": "RAKA-ECOR-CI-COM-001", 
      //   "source_ip": "10.41.0.3", 
      //   "status": "Up", 
      //   "target": "", 
      //   "target_ip": "10.32.0.4", 
      //   "upload": 0.01, 
      //   "upload_utilization": 0.0
      // }, 
      // {
      //   "device_b_ip": "10.76.0.4", 
      //   "download": 0.01, 
      //   "download_utilization": 0.001, 
      //   "errors": "in-0, out-0", 
      //   "high_speed": 1000, 
      //   "id": "edge-36", 
      //   "interface_a": "Te0/0/0/22.811", 
      //   "interface_b": "Gi1/3/7.811", 
      //   "label": "40 GB", 
      //   "packet_drops": "in-1, out-0", 
      //   "source": "RAKA-ECOR-CI-COM-001", 
      //   "source_ip": "10.41.0.3", 
      //   "status": "Up", 
      //   "target": "", 
      //   "target_ip": "10.76.0.4", 
      //   "upload": 0.01, 
      //   "upload_utilization": 0.001
      // }, 
      // {
      //   "device_b_ip": "10.35.0.4", 
      //   "download": 0.01, 
      //   "download_utilization": 0.001, 
      //   "errors": "in-0, out-0", 
      //   "high_speed": 1000, 
      //   "id": "edge-37", 
      //   "interface_a": "Te0/0/0/22.809", 
      //   "interface_b": "Gi0/0/3.809", 
      //   "label": "40 GB", 
      //   "packet_drops": "in-2, out-0", 
      //   "source": "RAKA-ECOR-CI-COM-001", 
      //   "source_ip": "10.41.0.3", 
      //   "status": "Up", 
      //   "target": "", 
      //   "target_ip": "10.35.0.4", 
      //   "upload": 0.01, 
      //   "upload_utilization": 0.001
      // }, 
      // {
      //   "device_b_ip": "10.64.150.151", 
      //   "download": 621.45, 
      //   "download_utilization": 6.214, 
      //   "errors": "in-0, out-0", 
      //   "high_speed": 10000.0, 
      //   "id": "edge-38", 
      //   "interface_a": "TenGigabitEthernet1/3/0.30", 
      //   "interface_b": "BE20.30", 
      //   "label": "40 GB ", 
      //   "packet_drops": "in-0, out-0", 
      //   "source": "FYHA-ECOR-CI-COM-001", 
      //   "source_ip": "10.83.0.3", 
      //   "status": "Up", 
      //   "target": "", 
      //   "target_ip": "10.64.150.151", 
      //   "upload": 1296.22, 
      //   "upload_utilization": 12.962
      // }, 
      // {
      //   "device_b_ip": "10.78.1.23", 
      //   "download": 310.0, 
      //   "download_utilization": 3.1, 
      //   "errors": "in-0, out-0", 
      //   "high_speed": 10000.0, 
      //   "id": "edge-39", 
      //   "interface_a": "TenGigabitEthernet1/3/0.60", 
      //   "interface_b": "BE20.60", 
      //   "label": "40 GB", 
      //   "packet_drops": "in-0, out-0", 
      //   "source": "FYHA-ECOR-CI-COM-001", 
      //   "source_ip": "10.83.0.3", 
      //   "status": "Up", 
      //   "target": "", 
      //   "target_ip": "10.78.1.23", 
      //   "upload": 31.65, 
      //   "upload_utilization": 0.316
      // }, 
      // {
      //   "device_b_ip": "10.41.0.3", 
      //   "download": 0.03, 
      //   "download_utilization": 0.0, 
      //   "errors": "in-0, out-0", 
      //   "high_speed": 40000.0, 
      //   "id": "edge-40", 
      //   "interface_a": "BE20.70", 
      //   "interface_b": "BE20.70", 
      //   "label": "40 GB", 
      //   "packet_drops": "in-1, out-0", 
      //   "source": "JED1-ECOR-CI-COM-001", 
      //   "source_ip": "10.78.0.3", 
      //   "status": "Up", 
      //   "target": "", 
      //   "target_ip": "10.41.0.3", 
      //   "upload": 0.04, 
      //   "upload_utilization": 0.0
      // }, 
      // {
      //   "device_b_ip": "10.41.1.82", 
      //   "download": 0.84, 
      //   "download_utilization": 0.004, 
      //   "errors": "in-0, out-0", 
      //   "high_speed": 20000.0, 
      //   "id": "edge-41", 
      //   "interface_a": "BE20.10", 
      //   "interface_b": "BE20.10", 
      //   "label": "40 GB", 
      //   "packet_drops": "in-0, out-0", 
      //   "source": "ADAM-ECOR-CI-COM-001", 
      //   "source_ip": "10.42.0.3", 
      //   "status": "Up", 
      //   "target": "", 
      //   "target_ip": "10.41.1.82", 
      //   "upload": 3.15, 
      //   "upload_utilization": 0.016
      // }, 
      // {
      //   "device_b_ip": "10.42.1.138", 
      //   "download": 3153.44, 
      //   "download_utilization": 15.767, 
      //   "errors": "in-0, out-0", 
      //   "high_speed": 20000.0, 
      //   "id": "edge-42", 
      //   "interface_a": "BE20.40", 
      //   "interface_b": "BE20.40", 
      //   "label": "40 GB", 
      //   "packet_drops": "in-0, out-0", 
      //   "source": "MLQA-ECOR-CI-COM-001", 
      //   "source_ip": "10.64.0.3", 
      //   "status": "Up", 
      //   "target": "", 
      //   "target_ip": "10.42.1.138", 
      //   "upload": 4629.07, 
      //   "upload_utilization": 23.145
      // }, 
      // {
      //   "device_b_ip": "10.42.1.138", 
      //   "download": 18.91, 
      //   "download_utilization": 0.189, 
      //   "errors": "in-0, out-0", 
      //   "high_speed": 10000.0, 
      //   "id": "edge-43", 
      //   "interface_a": "TenGigabitEthernet1/3/0.20", 
      //   "interface_b": "BE20.20", 
      //   "label": "40 GB", 
      //   "packet_drops": "in-0, out-0", 
      //   "source": "FYHA-ECOR-CI-COM-001", 
      //   "source_ip": "10.83.0.3", 
      //   "status": "Up", 
      //   "target": "", 
      //   "target_ip": "10.42.1.138", 
      //   "upload": 250.61, 
      //   "upload_utilization": 2.506
      // }, 
      // {
      //   "device_b_ip": "10.66.1.152", 
      //   "download": 3319.27, 
      //   "download_utilization": 16.596, 
      //   "errors": "in-0, out-0", 
      //   "high_speed": 20000.0, 
      //   "id": "edge-44", 
      //   "interface_a": "BE20.10", 
      //   "interface_b": "BE20.10", 
      //   "label": "40 GB", 
      //   "packet_drops": "in-0, out-0", 
      //   "source": "MLQA-ECOR-CI-COM-001", 
      //   "source_ip": "10.64.0.3", 
      //   "status": "Up", 
      //   "target": "", 
      //   "target_ip": "10.66.1.152", 
      //   "upload": 2282.66, 
      //   "upload_utilization": 11.413
      // }, 
      // {
      //   "device_b_ip": "10.66.1.152", 
      //   "download": 14.97, 
      //   "download_utilization": 0.037, 
      //   "errors": "in-0, out-0", 
      //   "high_speed": 40000.0, 
      //   "id": "edge-45", 
      //   "interface_a": "BE20.80", 
      //   "interface_b": "BE20.80", 
      //   "label": "40 GB", 
      //   "packet_drops": "in-0, out-0", 
      //   "source": "JED1-ECOR-CI-COM-001", 
      //   "source_ip": "10.78.0.3", 
      //   "status": "Up", 
      //   "target": "", 
      //   "target_ip": "10.66.1.152", 
      //   "upload": 12.78, 
      //   "upload_utilization": 0.032
      // }
    ],
    "node_list": [
      {
        // "cpu_utilization": 19, 
        // "device": "MLQA-ECOR-CI-COM-001", 
        "id": "r1",
        "type": "router",
        "name":"r1",
        // "interface": "TenGigE0/0/0/12.922", 
        // "ip": "10.64.0.3", 
        // "location": "inner", 
        // "memory_utilization": 41.74, 
        "position": {
          "x": 510.0, 
          "y": 400.0
        }
      }, 
      {
        // "cpu_utilization": 10, 
        // "device": "SULM-ECOR-CI-COM-001", 
        "id": "r2",
         "type": "router",
         "name": "r2",
        
        
        // "interface": "Te0/0/0/22.923", 
        // "ip": "10.66.0.3", 
        // "location": "inner", 
        // "memory_utilization": 41.74, 
        "position": {
          "x": 750.0, 
          "y": 420.0
        }
      }, 
      {
        // "cpu_utilization": 1, 
        // "device": "FYHA-ECOR-CI-COM-001", 
        "id": "r3", 
         "type": "router",
         "name": "r3",
        // "interface": "TenGigabitEthernet1/1/0.710", 
        // "ip": "10.83.0.3", 
        // "location": "inner", 
        // "memory_utilization": 11.23, 
        "position": {
          "x": 990.0, 
          "y": 370.0
        }
      }, 
      {
        // "cpu_utilization": 3, 
        // "device": "JED1-ECOR-CI-COM-001", 
        "id": "r4", 
         "type": "router",
         "name": "r4",
        // "interface": "GigabitEthernet0/0/0/1", 
        // "ip": "10.78.0.3", 
        // "location": "inner", 
        // "memory_utilization": 40.59, 
        "position": {
          "x": 1300.0, 
          "y": 500.0
        }
      }, 
      {
        // "cpu_utilization": 8, 
        // "device": "ADAM-ECOR-CI-COM-001", 
        "id": "r5", 
         "type": "router",
         "name": "r5",
        // "interface": "Te0/0/0/22.800", 
        // "ip": "10.42.0.3", 
        // "location": "inner", 
        // "memory_utilization": 41.83, 
        "position": {
          "x": 750, 
          "y": 570
        }
      }, 
      {
        // "cpu_utilization": 3, 
        // "device": "RAKA-ECOR-CI-COM-001", 
        "id": "r6", 
         "type": "router",
         "name": "r6",
        // "interface": "Te0/0/0/22.801", 
        // "ip": "10.41.0.3", 
        // "location": "inner", 
        // "memory_utilization": 40.86, 
        "position": {
          "x": 1050, 
          "y": 520
        }
      }, 
      {
        // "cpu_utilization": 4, 
        // "device": "BURD-ECOR-CI-COM-001", 
        "id": "r7", 
         "type": "router",
         "name": "r7",
        // "interface": "be10.922", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 40.92, 
        "position": {
          "x": 880, 
          "y": 700
        }
      }, 
      {
        // "cpu_utilization": 4, 
        // "device": "BURD-ECOR-CI-COM-002", 
        "id": "r8", 
         "type": "router",
         "name": "r8",
        // "interface": "BE10.923", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 40.86, 
        "position": {
          "x": 660, 
          "y": 770
        }
      }, 
      {
        // "cpu_utilization": 2, 
        // "device": "DANA-ECOR-CI-COM-001", 
        "id": "r9", 
         "type": "router",
         "name": "r9",
        // "interface": "Gi4/11.908", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 13.66, 
        "position": {
          "x": 580, 
          "y": 550
        }
      }, 
      {
        // "cpu_utilization": 2, 
        // "device": "DANA-ECOR-CI-COM-002", 
        "id": "r10", 
         "type": "router",
         "name": "r10",
        // "interface": "Gi4/11.909", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 13.64, 
        "position": {
          "x": 520, 
          "y": 700
        }
      }, 
      {
        // "cpu_utilization": 2, 
        // "device": "ERJA-ECOR-CI-COM-001", 
        "id": "r11", 
         "type": "router",
         "name": "r11",
        // "interface": "Gi0/0/3.916", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 56.14, 
        "position": {
          "x": 1033, 
          "y": 700
        }
      }, 
      {
        // "cpu_utilization": 0, 
        // "device": "ERJA-ECOR-CI-COM-002", 
        "id": "r12", 
         "type": "router",
         "name": "r12",
        // "interface": "Gi0/0/3.917 ", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 56.05, 
        "position": {
          "x": 1150, 
          "y": 770
        }
      }, 
      {
        // "cpu_utilization": 1, 
        // "device": "KHRJ-ECOR-CI-COM-001", 
        "id": "r13", 
         "type": "router",
         "name": "r13",
        // "interface": "Gi0/3/1.914", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 56.46, 
        "position": {
          "x": 1260, 
          "y": 650
        }
      }, 
      {
        // "cpu_utilization": 3, 
        // "device": "KHRJ-ECOR-CI-COM-002", 
        "id": "i1", 
         "type": "interface",
         "name": "i1",
        // "interface": "Gi0/3/1.915", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 56.46, 
        "position": {
          "x": 623, 
          "y": 200
        }
      }, 
      {
        // "cpu_utilization": 13, 
        // "device": "MALZ-ECOR-CI-COM-001", 
        "id": "i2", 
         "type": "interface",
         "name": "i2",
        // "interface": "Te0/0/0/23.930", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 40.25, 
        "position": {
          "x": 1380, 
          "y": 200
        }
      }, 
      {
        // "cpu_utilization": 5, 
        // "device": "MALZ-ECOR-CI-COM-002", 
        "id": "i3", 
         "type": "interface",
         "name": "i3",
        // "interface": "Te0/0/0/23.931", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 40.28, 
        "position": {
          "x": 220, 
          "y": 250
        }
      }, 
      {
        // "cpu_utilization": 0, 
        // "device": "MLQ2-ECOR-CI-COM-001", 
        "id": "i4", 
         "type": "interface",
         "name": "i4",
        // "interface": "Te1/1/0.920", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 31.97, 
        "position": {
          "x": 220, 
          "y": 361
        }
      }, 
      {
        // "cpu_utilization": 1, 
        // "device": "MLQ2-ECOR-CI-COM-002", 
        "id": "i5", 
         "type": "interface",
         "name": "i5",
        // "interface": "Te1/1/0.921", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 31.93, 
        "position": {
          "x": 250, 
          "y": 520
        }
      }, 
      {
        // "cpu_utilization": 11, 
        // "device": "SULY-ECOR-CI-COM-001", 
        "id": "i6", 
         "type": "interface",
         "name": "i6",
        // "interface": "Bundle-Ether22.900", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 41.56, 
        "position": {
          "x": 200, 
          "y": 700
        }
      }, 
      {
        // "cpu_utilization": 7, 
        // "device": "SULY-ECOR-CI-COM-002", 
        "id": "i7", 
         "type": "interface",
         "name": "i7",
        // "interface": "BE22.900", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 42.53, 
        "position": {
          "x": 200, 
          "y": 850
        }
      }, 
      {
        // "cpu_utilization": 0, 
        // "device": "UNZH-ECOR-CI-COM-001", 
        "id": "i8", 
         "type": "interface",
         "name": "i8",
        // "interface": "Gi1/4.910", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 6.41, 
        "position": {
          "x": 430, 
          "y": 950
        }
      }, 
      {
        // "cpu_utilization": 1, 
        // "device": "UNZH-ECOR-CI-COM-002", 
        "id": "i9", 
         "type": "interface",
         "name": "i9",
        // "interface": "Gi1/4.911", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 6.38, 
        "position": {
          "x": 850, 
          "y": 950
        }
      }, 
      {
        // "cpu_utilization": 2, 
        // "device": "ABHA-ECOR-CI-COM-001", 
        "id": "i10", 
         "type": "interface",
         "name": "i10",
        // "interface": "Gi3/1.710", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 31.5, 
        "position": {
          "x": 1161, 
          "y": 950
        }
      }, 
      {
        // "cpu_utilization": 2, 
        // "device": "ABHA-ECOR-CI-COM-002", 
        "id": "i11", 
         "type": "interface",
         "name": "i11",
        // "interface": "Gi3/1.719", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 31.51, 
        "position": {
          "x": 1500, 
          "y": 920
        }
      },
       
      {
        // "cpu_utilization": 1, 
        // "device": "JELS-ECOR-CI-COM-001", 
        "id": "i12", 
         "type": "interface",
         "name": "i12",
        // "interface": "GigabitEthernet0/1/3", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 22.05, 
        "position": {
          "x": 1700, 
          "y": 320
        }
      }, 
      {
        // "cpu_utilization": 3, 
        // "device": "JELS-ECOR-CI-COM-002", 
        "id": "i13", 
         "type": "interface",
         "name": "i13",
        // "interface": " Gig0/1/0", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 22.39, 
        "position": {
          "x": 1784, 
          "y": 460
        }
      }, 
      {
        // "cpu_utilization": 4, 
        // "device": "OBHR-ECOR-CI-COM-001", 
        "id": "i14", 
         "type": "interface",
         "name": "i14",
        // "interface": "Gi0/2/0.700 ", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 21.87, 
        "position": {
          "x": 1684, 
          "y": 660
        }
      }, 
      {
        // "cpu_utilization": 3, 
        // "device": "OBHR-ECOR-CI-COM-002", 
        "id": "c1", 
         "type": "community",
         "name": "c1",
        // "interface": "Gi0/2/0.714", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 21.87, 
        "position": {
          "x": 218, 
          "y": 50
        }
      }, 
      {
        // "cpu_utilization": 3, 
        // "device": "SAFA-ECOR-CI-COM-001", 
        "id": "c2", 
         "type": "community",
         "name": "c2",
        // "interface": "Gi0/2/0.706", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 56.4, 
        "position": {
          "x": 550, 
          "y": 50
        }
      }, 
      {
        // "cpu_utilization": 2, 
        // "device": "SAFA-ECOR-CI-COM-002", 
        "id": "c3", 
         "type": "community",
         "name": "c3",
        // "interface": "Gi0/2/0.717", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 56.45, 
        "position": {
          "x": 850, 
          "y": 50
        }
      }, 
      {
        // "cpu_utilization": 2, 
        // "device": "SHRY-ECOR-CI-COM-001", 
        "id": "c4", 
         "type": "community",
         "name": "c4",
        // "interface": "Gi0/0/2.704", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 21.79, 
        "position": {
          "x": 1250, 
          "y": 50
        }
      }, 
      {
        // "cpu_utilization": 1, 
        // "device": "SHRY-ECOR-CI-COM-002", 
        "id": "c5", 
         "type": "community",
         "name": "c5",
        // "interface": "Gi0/0/2.716", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 21.8, 
        "position": {
          "x": 1650, 
          "y": 50
        }
      }, 
      // ==== added by me ===== 
      {
        // "cpu_utilization": 1, 
        // "device": "SHRY-ECOR-CI-COM-002", 
        "id": "c6", 
         "type": "community",
         "name": "c6",
        // "interface": "Gi0/0/2.716", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 21.8, 
        "position": {
          "x": 2170, 
          "y": 400
        }
      }, 

      {
        // "cpu_utilization": 1, 
        // "device": "SHRY-ECOR-CI-COM-002", 
        "id": "c7", 
         "type": "community",
         "name": "c7",
        // "interface": "Gi0/0/2.716", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 21.8, 
        "position": {
          "x": 2170, 
          "y": 1000
        }
      }, 

      // =======================
      {
        // "cpu_utilization": 0, 
        // "device": "SHWQ-ECOR-CI-COM-001", 
        "id": "c8", 
         "type": "community",
         "name": "c8",
        // "interface": "Gi0/0/2.702", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 21.8, 
        "position": {
          "x": 2170, 
          "y": 200
        }
      }, 
      {
        // "cpu_utilization": 1, 
        // "device": "SHWQ-ECOR-CI-COM-002", 
        "id": "c9", 
         "type": "community",
         "name": "c9",
        // "interface": "Gi0/0/2.715", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 21.82, 
        "position": {
          "x": 2170,  
          "y": 475
        }
      }, 
      {
        // "cpu_utilization": 1, 
        // "device": "SULT-ECOR-CI-COM-001", 
        "id": "c10", 
         "type": "community",
         "name": "c10",
        // "interface": "Gi0/1/0.918", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 56.4, 
        "position": {
          "x": 2170,  
          "y": 581
        }
      }, 
      {
        // "cpu_utilization": 1, 
        // "device": "SULT-ECOR-CI-COM-002", 
        "id": "c11", 
         "type": "community",
         "name": "c11",
        // "interface": "Gi0/1/0.721", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 21.77, 
        "position": {
          "x": 2170,  
          "y": 688
        }
      }, 
      {
        // "cpu_utilization": 1, 
        // "device": "DHRN-ECOR-CI-COM-001", 
        "id": "c12", 
         "type": "community",
         "name": "c12",
        // "interface": "Gi0/0/3.808", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 55.97, 
        "position": {
          "x": 350, 
          "y": 1100
        }
      }, 
      {
        // "cpu_utilization": 1, 
        // "device": "DHRN-ECOR-CI-COM-002", 
        "id": "c13", 
         "type": "community",
         "name": "c13",
        // "interface": "Gi0/0/3.809", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 21.73, 
        "position": {
          "x": 580, 
          "y": 1100
        }
      }, 
      {
        // "cpu_utilization": 1, 
        // "device": "HUFO-ECOR-CI-COM-001", 
        "id": "c14", 
         "type": "community",
         "name": "c14",
        // "interface": "Gi1/3/7.810", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 56.45, 
        "position": {
          "x": 810, 
          "y": 1100
        }
      }, 
      {
        // "cpu_utilization": 1, 
        // "device": "HUFO-ECOR-CI-COM-002", 
        "id": "c15", 
         "type": "community",
         "name": "c15",
        // "interface": "Gi1/3/7.811", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 56.17, 
        "position": {
          "x": 1040, 
          "y": 1100
        }
      }, 
      {
        // "cpu_utilization": 1, 
        // "device": "RSHD-ECOR-CI-COM-001", 
        "id": "c16", 
         "type": "community",
         "name": "c16",
        // "interface": "Te4/2.800", 
        // "ip": "", 
        // "location": "outer", 
        // "memory_utilization": 13.9, 
        "position": {
          "x": 1270, 
          "y": 1100
        }
      }, 
      
        {
          // "cpu_utilization": 2, 
          // "device": "RSHD-ECOR-CI-COM-002", 
          "id": "c17", 
           "type": "community",
           "name": "c17",
          // "interface": "Te4/2.801", 
          // "ip": "", 
          // "location": "outer", 
          // "memory_utilization": 13.86, 
          "position": {
            "x": 1700, 
            "y": 1100
          }

      }
    ]
  }
  export default Data
  